random.assign <- function(param, n){
  param$mass  <- rnorm(n, mean = 7.78, sd = 1.19)
  param$pFat  <- abs(rnorm(n, mean = 1.68, sd = 0.88)/param$mass)
  param$pLean  <- abs(rnorm(n, mean = 4.14, sd = 0.93)/param$mass)
  param$RMR  <- 1.0895 + (0.744*log(param$mass))
  param$rEWL  <- rnorm(n, mean = 0.138, sd = 0.04)
  param$TMRmin  <- abs(rnorm(n, mean = 0.07, sd = 0.06))
  param$Teu <- rep(param$Teu, n)
  param$Tlc <- rep(param$Tlc, n)
  param$Ttormin <- rep(param$Ttormin, n)
  param$Ceu <- rep(param$Ceu, n)
  param$Ct <- rep(param$Ct, n)
  param$S <- rep(param$S, n)
  param$ttormax <- rep(param$ttormax, n)
  param$teu <- rep(param$teu, n)
  param$WR <- rep(param$WR, n)
  param$CR <- rep(param$CR, n)
  param$mrPd <- rep(param$mrPd, n)
  param$aPd <- rep(param$aPd, n)
  param$rPd <- rep(param$rPd, n)
  param$pMass.i <- rep(param$pMass.i, n)
  param$pMass <- rep(param$pMass, n)
  param$pFly <- rep(param$pFly, n)
  return(param)
}
